const dgram = require('dgram');
const { getSettings } = require('./settings');

/**
 * Normalizes a room name to a standard format suitable for Loxone UDP commands.
 * Matches lowercase, no special characters, no spaces.
 * e.g., "Living Room" -> "livingroom", "Küche" -> "kueche", "Bad" -> "bad"
 * @param {string} roomName - The raw Sonos room name.
 * @returns {string} The normalized room name.
 */
function normalizeRoomName(roomName) {
  if (!roomName) return '';
  return roomName
    .toLowerCase()
    .replace(/ä/g, 'ae')
    .replace(/ö/g, 'oe')
    .replace(/ü/g, 'ue')
    .replace(/ß/g, 'ss')
    .replace(/[^a-z0-9]/g, ''); // Remove spaces, punctuation, etc.
}

/**
 * Sends a UDP packet to Loxone.
 * @param {string} message - The text message to send.
 */
function sendUdp(message) {
  const settings = getSettings();
  const ip = settings.loxoneIp;
  const port = settings.loxonePort;

  if (!ip) {
    console.warn('[Loxone] UDP IP not configured. Skipping status update:', message);
    return;
  }

  const client = dgram.createSocket('udp4');
  const buffer = Buffer.from(message);

  client.send(buffer, 0, buffer.length, port, ip, (err) => {
    client.close();
    if (err) {
      console.error(`[Loxone] Failed to send UDP message to ${ip}:${port} - Error:`, err);
    } else {
      console.log(`[Loxone] UDP Sent -> ${ip}:${port} - "${message}"`);
    }
  });
}

/**
 * Sends the playback state of a Sonos room to Loxone.
 * @param {string} roomName - The raw room name.
 * @param {boolean|number} isPlaying - True/1 if playing, False/0 if paused/stopped.
 */
function sendPlayStatus(roomName, isPlaying) {
  const normName = normalizeRoomName(roomName);
  const value = isPlaying ? 1 : 0;
  sendUdp(`sonos.${normName}.play ${value}`);
}

/**
 * Sends the volume of a Sonos room to Loxone.
 * @param {string} roomName - The raw room name.
 * @param {number} volume - The volume level (0-100).
 */
function sendVolumeStatus(roomName, volume) {
  const normName = normalizeRoomName(roomName);
  const value = Math.max(0, Math.min(100, Math.round(volume)));
  sendUdp(`sonos.${normName}.volume ${value}`);
}

/**
 * Generates the Loxone Virtual Input UDP XML template for the given rooms.
 * @param {string[]} rooms - List of Sonos room names.
 * @returns {string} The generated XML string.
 */
function generateLoxoneXml(rooms) {
  const settings = getSettings();
  const port = settings.loxonePort || 7777;

  let xml = '<?xml version="1.0" encoding="utf-8"?>\n';
  xml += `<VirtualInUdp HintText="" Title="SonosLoxoneBridge" Comment="Auto-generated by SonosLoxoneBridge" Address="" Port="${port}">\n`;
  xml += '\t<Info templateType="1" minVersion="17000331"/>\n';

  rooms.forEach(room => {
    const norm = normalizeRoomName(room);
    const escapedRoom = room.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    
    // 1. Playback Command
    xml += `\t<VirtualInUdpCmd Title="Sonos ${escapedRoom} Play" Comment="" Address="" Check="sonos.${norm}.play \\v" Signed="true" Analog="false" SourceValLow="0" DestValLow="0" SourceValHigh="1" DestValHigh="1" DefVal="0" MinVal="0" MaxVal="1" Unit="" HintText=""/>\n`;
    
    // 2. Volume Command
    xml += `\t<VirtualInUdpCmd Title="Sonos ${escapedRoom} Volume" Comment="" Address="" Check="sonos.${norm}.volume \\v" Signed="true" Analog="true" SourceValLow="0" DestValLow="0" SourceValHigh="100" DestValHigh="100" DefVal="0" MinVal="0" MaxVal="100" Unit="&lt;v&gt; %" HintText=""/>\n`;
  });

  xml += '</VirtualInUdp>\n';
  return xml;
}

module.exports = {
  normalizeRoomName,
  sendPlayStatus,
  sendVolumeStatus,
  generateLoxoneXml,
  sendUdp
};
